[workspace]

resolver = "2"

members = [
    "parser",
    "xtask",
    "server"
]

[workspace.dependencies]
parser = { path = "./parser", version = "0.1.0" }

anyhow = "1.0.75"
indexmap = "2.1.0"
itertools = "0.12.0"
proc-macro2 = "1.0.70"
quote = "1.0.33"
ungrammar = "1.16.1"
xshell = "0.2.5"
rowan = "0.15.15"
logos = "0.12.0"
