[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rowan.workspace = true
anyhow.workspace = true
logos.workspace = true

[dev-dependencies]
expect-test.workspace = true
